<?php
namespace Novel\Consts\Idents;


class KeywordNames
{
	const ABSTRACT 			= 'abstract';
	const AND 				= 'and';
	const ARRAY_CONSTRUCTOR = 'array constructor';
	const AS 				= 'as';
	const BREAK 			= 'break';
	const CALLABLE 			= 'callable';
	const CASE 				= 'case';
	const CATCH 			= 'catch';
	const CLASS_NAME 		= 'class';
	const CLONE 			= 'clone';
	const CONST 			= 'const';
	const CONTINUE 			= 'continue';
	const DECLARE 			= 'declare';
	const DEFAULT 			= 'default';
	const DIE 				= 'die';
	const DO 				= 'do';
	const ECHO 				= 'echo';
	const ELSE 				= 'else';
	const ELSE_IF 			= 'else if';
	const EMPTY 			= 'empty';
	const END_DECLARE 		= 'end declare';
	const END_FOREACH 		= 'end foreach';
	const END_FOR 			= 'end for';
	const END_IF 			= 'end if';
	const END_SWITCH 		= 'end switch';
	const END_WHILE 		= 'end while';
	const EVAL 				= 'eval';
	const EXIT 				= 'exit';
	const EXTENDS 			= 'extends';
	const FINAL 			= 'final';
	const FINALLY 			= 'finally';
	const FOREACH 			= 'foreach';
	const FOR 				= 'for';
	const FUNCTION 			= 'function';
	const GLOBAL 			= 'global';
	const GOTO 				= 'goto';
	const IF 				= 'if';
	const IMPLEMENTS 		= 'implements';
	const INCLUDE 			= 'include';
	const INCLUDE_ONCE 		= 'include once';
	const INSTANCE_OF 		= 'instance of';
	const INSTEAD_OF 		= 'instead of';
	const INTERFACE 		= 'interface';
	const ISSET 			= 'isset';
	const LIST 				= 'list';
	const NAMESPACE 		= 'namespace';
	const NEW 				= 'new';
	const OR 				= 'or';
	const PRINT 			= 'print';
	const PRIVATE 			= 'private';
	const PROTECTED 		= 'protected';
	const PUBLIC 			= 'public';
	const REQUIRE 			= 'require';
	const REQUIRE_ONCE 		= 'require once';
	const RETURN 			= 'return';
	const STATIC 			= 'static';
	const SWITCH 			= 'switch';
	const THROW 			= 'throw';
	const TRAIT 			= 'trait';
	const TRY 				= 'try';
	const UNSET 			= 'unset';
	const USE 				= 'use';
	const VAR 				= 'var';
	const WHILE 			= 'while';
	const XOR 				= 'xor';
	const YIELD 			= 'yield';
}