<?php
namespace Novel\Consts\Symbols;


class KeywordNames
{
	public const ABSTRACT 			= 'abstract';
	public const AND 				= 'and';
	public const ARRAY_CONSTRUCTOR 	= 'array_constructor';
	public const AS 				= 'as';
	public const BREAK 				= 'break';
	public const CALLABLE 			= 'callable';
	public const CASE 				= 'case';
	public const CATCH 				= 'catch';
	public const CLASS_NAME 		= 'class';
	public const CLONE 				= 'clone';
	public const CONST 				= 'const';
	public const CONTINUE 			= 'continue';
	public const DECLARE 			= 'declare';
	public const DEFAULT 			= 'default';
	public const DIE 				= 'die';
	public const DO 				= 'do';
	public const ECHO 				= 'echo';
	public const ELSE 				= 'else';
	public const ELSE_IF 			= 'else_if';
	public const EMPTY 				= 'empty';
	public const END_DECLARE 		= 'end_declare';
	public const END_FOREACH 		= 'end_foreach';
	public const END_FOR 			= 'end_for';
	public const END_IF 			= 'end_if';
	public const END_SWITCH 		= 'end_switch';
	public const END_WHILE 			= 'end_while';
	public const EVAL 				= 'eval';
	public const EXIT 				= 'exit';
	public const EXTENDS 			= 'extends';
	public const FINAL 				= 'final';
	public const FINALLY 			= 'finally';
	public const FOREACH 			= 'foreach';
	public const FOR 				= 'for';
	public const FUNCTION 			= 'function';
	public const GLOBAL 			= 'global';
	public const GOTO 				= 'goto';
	public const IF 				= 'if';
	public const IMPLEMENTS 		= 'implements';
	public const INCLUDE 			= 'include';
	public const INCLUDE_ONCE 		= 'include_once';
	public const INSTANCE_OF 		= 'instance_of';
	public const INSTEAD_OF 		= 'instead_of';
	public const INTERFACE 			= 'interface';
	public const ISSET 				= 'isset';
	public const LIST 				= 'list';
	public const NAMESPACE 			= 'namespace';
	public const NEW 				= 'new';
	public const OR 				= 'or';
	public const PRINT 				= 'print';
	public const PRIVATE 			= 'private';
	public const PROTECTED 			= 'protected';
	public const PUBLIC 			= 'public';
	public const REQUIRE 			= 'require';
	public const REQUIRE_ONCE 		= 'require_once';
	public const RETURN 			= 'return';
	public const STATIC 			= 'static';
	public const SWITCH 			= 'switch';
	public const THROW 				= 'throw';
	public const TRAIT 				= 'trait';
	public const TRY 				= 'try';
	public const UNSET 				= 'unset';
	public const USE 				= 'use';
	public const VAR 				= 'var';
	public const WHILE 				= 'while';
	public const XOR 				= 'xor';
	public const YIELD 				= 'yield';
}